/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package KBank.BancoDigital.DIO;
import model.Cliente;
import model.ContaCorrentePF;
import model.ContaPF;
import model.ContaPoupancaPF;

public class App {
    public static void main(String[] args) {
        ContaPF cc1 = new ContaCorrentePF(new Cliente());
        cc1.getClient().setName("Gabriel");
        cc1.deposit(1000);
        ContaPF cp1 = new ContaPoupancaPF(cc1.getClient());
        cp1.deposit(1000);
        cc1.transfer(100, cp1);
        cp1.withdraw(1000);
        cc1.withdraw(1000);
    }
}
